[DERBY-635] Client socket connection doesn t report real socket exception <p>When opening a connection with a network url: jdbc:derby://localhost:4000/data<br/>
The netagent catchs the PrivilegedActionException but doesn t report the checked exception in it.<br/>
Changing these lines<br/>
        try </p>
{
            socket_ = (java.net.Socket) java.security.AccessController.doPrivileged(new OpenSocketAction(server, port));
        } catch (java.security.PrivilegedActionException e) {
            throw new DisconnectException(this,
                    e.getClass().getName() +   : Error opening socket to server   + server +   on port   + port +   with message :   + e.getMessage());
        }<br/>
To This returns the check exception information:<br/>
        try {            socket_ = (java.net.Socket) java.security.AccessController.doPrivileged(new OpenSocketAction(server, port));        }
<p> catch (java.security.PrivilegedActionException e) </p>
{
            throw new DisconnectException(this,
                    e.getException().getClass().getName() +   : Error opening socket to server   + server +   on port   + port +   with message :   + e.getException().getMessage());
        }


<p>It currently reports messages like this:<br/>
Caused by: java.sql.SQLException: org.apache.derby.client.am.SqlException: java.security.PrivilegedActionException : Error opening socket to server localhost on port 1527 with message : null</p>

<p>With this fix it reports:<br/>
org.apache.derby.client.am.DisconnectException: java.net.ConnectException : Error opening socket to server localhost on port 1527 with message : Connection refused: connect</p>
